services:
  - type: web
    name: bakery-studio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn ui:app --host 0.0.0.0 --port $PORT
